apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gin-k8s-auth-go-k8s-middleware-b6hn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gin-k8s-auth-go-k8s-middleware-b6hn
    app.kubernetes.io/part-of: go-k8s-middleware
  name: gin-k8s-auth-go-k8s-middleware-b6hn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: gin-k8s-auth-go-k8s-middleware-b6hn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: gin-k8s-auth-go-k8s-middleware-b6hn
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mkovarik-tenant/go-k8s-middleware/gin-k8s-auth-go-k8s-middleware-b6hn@sha256:ede99d97010e7bff79919fb2104adbf7cbcbb31a726a2fb29ec40c9f556e41aa
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
