apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gin-k8s-auth-go-k8s-middleware-b6hn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gin-k8s-auth-go-k8s-middleware-b6hn
    app.kubernetes.io/part-of: go-k8s-middleware
  name: gin-k8s-auth-go-k8s-middlvgz3
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: gin-k8s-auth-go-k8s-middleware-b6hn
    weight: null
status: {}
